# Use postgres/example user/password credentials
version: '3.1'

services:
  application:
    container_name: graphql-app
    image: devwuu/basic:1.0
    ports:
      - 4000:4000
    networks:
      - basic

networks:
  basic: {}